CREATE TABLE IF NOT EXISTS `assets` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `asset_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `image1` VARCHAR(255) DEFAULT NULL,
  `image2` VARCHAR(255) DEFAULT NULL,
  `model` TEXT DEFAULT NULL,
  `cost` DECIMAL(15,2) DEFAULT 0.00,
  `quantity` INT(11) DEFAULT 1,
  `invoice_number` VARCHAR(100) DEFAULT NULL,
  `inventory_date` DATE DEFAULT NULL,
  `inventory_taker` VARCHAR(100) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
